services:
  - type: web
    name: ytob
    runtime: node
    plan: free
    rootDir: backend  # Specify the directory containing your backend code
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: PYTHON_VERSION
        value: 3.11.4