services:
  - type: web
    name: ytob
    plan: free
    env: python
    buildCommand: |
      # Install Node.js dependencies
      cd backend
      pip install -r requirements.txt && npm install
    startCommand: |
      # Start your Node.js application (if applicable)
      cd backend
      npm start
      
