services:
  - type: web
    name: ytob
    env: node
    buildCommand: |
      # Install Node.js dependencies
      npm install
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: |
      # Start your Node.js application (if applicable)
      npm start
      
